.TH telnet_init 3 LIBTELNET "" "TELNET Library"

.SH NAME
\fBtelnet_free\fP - release resources for TELNET state tracker

.SH SYNOPSIS
.PP
\fB#include <libtelnet.h>\fP
.sp
.B "void telnet_free( telnet_t *\fItelnet\fP );"

.SH DESCRIPTION
.PP
The \fBtelnet_free\fP function deallocates resources associated with a prior
call to \fBtelnet_init\fP.

.SH SEE ALSO
.PP
\fBlibtelnet\fR(3), \fBtelnet_init\fR(3)
