.TH telnet_finish_sb 3 LIBTELNET "" "TELNET Library"

.SH NAME
\fBtelnet_finish_sb\fP - finish a TELNET sub-negotiation command

.SH SYNOPSIS
.PP
\fB#include <libtelnet.h>\fP
.sp
.B "void telnet_finish_sb(telnet_t *\fBtelnet\fR);"

.SH DESCRIPTION
.PP
The \fBtelnet_finish_sb\fR function sends the TELNET command to complete a sub-negotiation sequence.  This must be called after a call to \fBtelnet_begin_sb\fR to complete a sub-negotiation.

The parameter \fItelnet\fP is a state tracker instance created by a prior call to \fBtelnet_init\fP.

.SH SEE ALSO
.PP
\fBlibtelnet\fR(3), \fBtelnet_send\fR(3), \fBtelnet_begin_sb\fR(3)
