.TH libtelnet 3 LIBTELNET "" "TELNET Library"

.SH NAME
\fBlibtelnet\fP - TELNET protocol processing library

.SH SYNOPSIS
.PP
\fB#include <libtelnet.h>\fP

.SH DESCRIPTION
.PP
\fBlibtelnet\fP is a library for handling the TELNET protocol.  It includes
routines for parsing incoming data from a remote peer as well as formatting
data to send to the remote peer.

\fBlibtelnet\fP uses a callback-oriented API, allowing application-specific
handling of various events.  The callback system is also used for buffering
outgoing protocol data, allowing the application to maintain control over the
actual socket connection.

Features supported include the full TELNET protocol, Q-method option
negotiation, ZMP, MCCP2, MSSP, and NEW-ENVIRON.

.SH CONFORMS TO
.PP
RFC854  - http://www.faqs.org/rfcs/rfc854.html
.br
RFC855  - http://www.faqs.org/rfcs/rfc855.html
.br
RFC1091 - http://www.faqs.org/rfcs/rfc1091.html
.br
RFC1143 - http://www.faqs.org/rfcs/rfc1143.html
.br
RFC1408 - http://www.faqs.org/rfcs/rfc1408.html
.br
RFC1572 - http://www.faqs.org/rfcs/rfc1572.html

.SH SEE ALSO
.PP
\fBtelnet_init\fR(3), \fBtelnet_free\fR(3), \fBtelnet_send\fR(3),
\fBtelnet_recv\fR(3), \fBtelnet_iac\fR(3), \fBtelnet_negotiate\fR(3)
