.TH telnet_printf 3 LIBTELNET "" "TELNET Library"

.SH NAME
\fBtelnet_printf\fP - send formatted text

.SH SYNOPSIS
.PP
\fB#include <libtelnet.h>\fP
.sp
.B "void telnet_printf(telnet_t *\fBtelnet\fR, unsigned char \fBcmd\fR, unsigned char \fIopt\fR);"

.SH DESCRIPTION
.PP
The \fBtelnet_printf\fP function sends formatted data across the connection.  Formatting is the same as in \fBprint\fP(3), and the result is sent to \fBtelnet_send\fP.  Note in particular that this means that the data sent by \fBtelnet_printf\fP is escaped..

The parameter \fItelnet\fP is a state tracker instance created by a prior call to \fBtelnet_init\fP.

The parameter \fIfmt\fP is a format string, as used by \fBprintf\fP.

.SH SEE ALSO
.PP
\fBlibtelnet\fR(3), \fBtelnet_send\fR(3), \fBtelnet_raw_printf\fR(3)
